### ISSUE TITLE
Getting no module found error

### ISSUE THREAD

**Issue by rsoorajs** [Sanix-Darker/ogramcloud#16]
![IMG_20200724_200023_877](https://user-images.githubusercontent.com/20116017/88402161-5e836e80-cde8-11ea-9b4b-ca9a19293858.jpg)

can you simplify the bot running part ? i am getting this error and trying run it on ubuntu 18

**Comment by rsoorajs** [comment]
file is uploading..

but didnt recieving in bot...also i change bot token too..the server process is running..but didnt getting any file on telegram

**Comment by Sanix-Darker** [comment]
Hey @telegrambotdev are you having error in your console or something ?

**Comment by Sanix-Darker** [comment]
Please, make sure to follow, how the original bot OgramBot have been made here : [OgramBot](https://github.com/sanix-darker/ogrambot)

**Comment by rsoorajs** [comment]
> Please, make sure to follow, how the original bot OgramBot have been made here : [OgramBot](https://github.com/sanix-darker/ogrambot)

yeah worked.i running both orgamcloud & orgambot. And yeah its working.
