### ISSUE TITLE
need uploading progress bar or percentage

### ISSUE THREAD

**Issue by rsoorajs** [Sanix-Darker/ogramcloud#19]
Need file uploading progress bar.when we try to upload a file it takes long time to upload.so if you added a progress bar or something,we can see the uploading progress.

**Comment by telegrambotdev** [comment]
Thanks in Advance

**Comment by Sanix-Darker** [comment]
Available on the last update !
![Peek 2020-07-29 18-33](https://user-images.githubusercontent.com/22576758/88834634-0c699100-d1cc-11ea-8479-71bedfb27aa9.gif)
